# modify from: https://github.com/isaacs/github/issues/415#issuecomment-561700485
name: Mirror AlphaPhase Repo
on:
  schedule:
    # Runs at 05:00, on day 12 of the month
    - cron:  '0 5 12 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git clone --bare 'https://github.com/AlphaGenes/AlphaPhase.git'
        cd AlphaPhase.git/
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/HighlanderLab/AlphaPhase.git"
        git push --mirror --force github
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
